frontend:
  replicaCount: 1
  image:
    repository: arunkumarravi08/login-frontend
    tag: 7
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80

backend:
  replicaCount: 1
  image:
    repository: arunkumarravi08/login-backend
    tag: 7
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000

mongodb:
  replicaCount: 1
  image:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
